### ISSUE TITLE
Testing: Use local coturn via testcontainers instead of Google

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/kotlin-ice-adapter#2]
The integration test currently uses a hardcoded stun server (stun.l.google.com, port 19302).
However this is not what we use at FAF. We use [coturn](https://github.com/coturn/coturn) running from a docker image.
The same could be achieved here, if we start if via [testcontainers](https://testcontainers.com/).

**Comment by antonkosse** [comment]
Hi @Brutus5000 

A few questions regarding usage of testcontainers: 
- I've noticed that in order to perform integration test with them, the host machine must have docker engine running on it. I am not that familiar with GitHub ops, their runners and specifically variety of them, but can it be a problem?

- Regarding mentioned coturn server and it's docker image: can you specify what version is used in FAF architecture? I was looking over GitOps stack that you have https://github.com/FAForever/gitops-stack/tree/main but not seeing any templates/yaml files for it. Or does it make sense to just use latest docker image for the server?

- Another point: I've cloned the project to my local machine, and can see that some unit and integration tests are already failing. The same happening in github jobs, Does it make sense to introduce any new changes to the tests themselves until their stabilized?

**Comment by Brutus5000** [comment]
Hello there,


> * I've noticed that in order to perform integration test with them, the host machine must have docker engine running on it. I am not that familiar with GitHub ops, their runners and specifically variety of them, but can it be a problem?

We use testcontainers already in the faf-java-api and their it works with a default runner [link to pipeline](https://github.com/FAForever/faf-java-api/blob/develop/.github/workflows/build.yaml)

> * Regarding mentioned coturn server and it's docker image: can you specify what version is used in FAF architecture? I was looking over GitOps stack that you have https://github.com/FAForever/gitops-stack/tree/main but not seeing any templates/yaml files for it. Or does it make sense to just use latest docker image for the server?

As a general info, gitops-stack is in the process of porting over everything from [faf-stack](https://github.com/FAForever/faf-stack). However, we no longer run coturn on the main server, but on dedicated cloud machines. You can just use the latest version of your distribution.

> * Another point: I've cloned the project to my local machine, and can see that some unit and integration tests are already failing. The same happening in github jobs, Does it make sense to introduce any new changes to the tests themselves until their stabilized?

They used to fail only in the runner, but looks like I finally broke them locally. :disappointed:
For the coturn change you can branch off of 767efb9cbc5f72d8625de31a07dcecbaff4b70e3 . There the IT are still working, but only locally :(
